version: '3'

services:
  flask_matflow:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: python manage.py
    ports:
      - "5000:5000"
    volumes:
      - ..:/flask_matflow
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    ports:
      - "27017:27017"
    volumes:
      #- mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: celery -A task.tasks worker --loglevel=info
    volumes:
      - ..:/flask_matflow
    depends_on:
      - redis

volumes:
  mongo-data:

